name: FastAPI CI/CD

on:
  push:
    branches: 
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:   
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
      
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Cache dependencies
      - name: Cache Virtual Environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      # Step 5: Run Tests
      - name: Run Tests
        run: |
          source .venv/bin/activate
          python -m unittest discover -s tests -p "*.py"

      # Step 6: Zip all files for deployment
      - name: Zip all files
        run: zip -r zan-ecommerce.zip ./*

      # Step 7: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zan-ecommerce
          path: zan-ecommerce.zip

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      # Step 1: Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: zan-ecommerce

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Upload to S3
      - name: Upload to S3
        run: aws s3 cp zan-ecommerce.zip s3://new-ecom-bucket/zan-ecommerce.zip

      # Step 4: Update Lambda Function
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
          --function-name new-ecom-lamb \
          --s3-bucket new-ecom-bucket \
          --s3-key zan-ecommerce.zip
